use std::env;
use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;
use toml::Value;

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let manifest_path = manifest_dir.join("Cargo.toml");
    let manifest_str = fs::read_to_string(&manifest_path)?;
    let manifest: Value = toml::from_str(&manifest_str)?;

    let dependencies = manifest
        .get("dependencies")
        .and_then(Value::as_table)
        .cloned()
        .unwrap_or_default();

    let mut adapters: Vec<String> = dependencies
        .into_iter()
        .filter_map(|(name, spec)| {
            if !name.starts_with("edgezero-adapter-") {
                return None;
            }
            let optional = if let Value::Table(table) = &spec {
                table
                    .get("optional")
                    .and_then(Value::as_bool)
                    .unwrap_or(false)
            } else {
                false
            };
            if !optional {
                return None;
            }
            let feature_env = format!(
                "CARGO_FEATURE_{}",
                name.replace('-', "_").to_ascii_uppercase()
            );
            println!("cargo:rerun-if-env-changed={feature_env}");
            let enabled = env::var(&feature_env).is_ok_and(|val| val == "1");
            enabled.then_some(name)
        })
        .collect();

    adapters.sort();
    adapters.dedup();

    let mut generated = String::from("// @generated by build.rs - do not edit manually.\n");

    if adapters.is_empty() {
        generated.push_str("// no adapters enabled for this build\n");
    } else {
        for adapter in adapters {
            let crate_ident = adapter.replace('-', "_");
            writeln!(
                generated,
                "#[expect(unused_imports, reason = \"adapter linked via feature gate\")]\n\
                 pub(crate) use {crate_ident} as _{crate_ident};",
            )?;
        }
    }

    let out_path = PathBuf::from(env::var("OUT_DIR")?).join("linked_adapters.rs");
    fs::write(out_path, generated)?;
    Ok(())
}
