[package]
name = "fixture-spin"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
serde_json.workspace = true
fixture-core.workspace = true
edgezero-core.workspace = true
edgezero-adapter-spin.workspace = true
spin-sdk = { version = "6.0", default-features = false }
anyhow = "1"

[lib]
crate-type = ["cdylib", "rlib"]
