use std::sync::Arc;

use crate::config_store::SpinConfigStore;
use crate::context::{parse_client_addr, SpinRequestContext};
use crate::key_value_store::SpinKvStore;
use crate::proxy::SpinProxyClient;
use crate::response::from_core_response;
use crate::secret_store::SpinSecretStore;
use crate::{resolve_store_settings, SpinStoreSettings};
use edgezero_core::app::App;
use edgezero_core::body::Body;
use edgezero_core::config_store::ConfigStoreHandle;
use edgezero_core::error::EdgeError;
use edgezero_core::http::{request_builder, HeaderValue, Method as CoreMethod, Request, Uri};
use edgezero_core::key_value_store::KvHandle;
use edgezero_core::manifest::ManifestLoader;
use edgezero_core::proxy::ProxyHandle;
use edgezero_core::secret_store::SecretHandle;
use spin_sdk::http::{IncomingRequest, Method as SpinMethod, Response as SpinResponse};

#[derive(Default)]
pub(crate) struct Stores {
    pub config_store: Option<ConfigStoreHandle>,
    pub kv: Option<KvHandle>,
    pub secrets: Option<SecretHandle>,
}

/// Convert a Spin `IncomingRequest` into an `EdgeZero` core `Request`.
///
/// Reads the full body into a buffered `Body::Once`, inserts
/// `SpinRequestContext` and a `ProxyHandle` into extensions.
///
/// # Errors
/// Returns [`EdgeError::bad_request`] when the request URI is invalid,
/// when the body cannot be read, or when building the core request fails.
#[inline]
pub async fn into_core_request(req: IncomingRequest) -> Result<Request, EdgeError> {
    let method = req.method();
    let path_with_query = req.path_with_query().unwrap_or_else(|| "/".to_owned());

    let uri: Uri = path_with_query
        .parse()
        .map_err(|err| EdgeError::bad_request(format!("invalid URI: {err}")))?;

    // Extract headers before consuming the request body. The WASI `headers()`
    // handle borrows the request and must be dropped before `into_body()`.
    let headers = req.headers();
    let header_entries = headers.entries();

    let mut builder = request_builder()
        .method(into_core_method(&method)?)
        .uri(uri);

    for (name, value) in &header_entries {
        match HeaderValue::from_bytes(value) {
            Ok(hval) => {
                builder = builder.header(name.as_str(), hval);
            }
            Err(_) => {
                log::warn!("dropping invalid request header value: {name}");
            }
        }
    }

    let client_addr = find_header_string(&header_entries, "spin-client-addr")
        .and_then(|raw| parse_client_addr(&raw));
    let full_url = find_header_string(&header_entries, "spin-full-url");

    // Drop the WASI resource handle before consuming the body.
    drop(headers);

    // Inbound body size is not capped at the adapter level. The Spin runtime
    // enforces its own request body limit (configurable via `spin.toml`), which
    // is consistent with how the Fastly and Cloudflare adapters delegate inbound
    // size enforcement to their respective platform runtimes.
    let body_bytes = req
        .into_body()
        .await
        .map_err(|err| EdgeError::bad_request(format!("failed to read request body: {err}")))?;

    let mut request = builder
        .body(Body::from(body_bytes))
        .map_err(|err| EdgeError::bad_request(format!("failed to build request: {err}")))?;

    SpinRequestContext::insert(
        &mut request,
        SpinRequestContext {
            client_addr,
            full_url,
        },
    );
    request
        .extensions_mut()
        .insert(ProxyHandle::with_client(SpinProxyClient));

    Ok(request)
}

/// Find a header value by name from pre-extracted header entries.
fn find_header_string(entries: &[(String, Vec<u8>)], name: &str) -> Option<String> {
    entries
        .iter()
        .find(|(header_name, _)| header_name.eq_ignore_ascii_case(name))
        .and_then(|(_, value)| String::from_utf8(value.clone()).ok())
}

/// Dispatch a Spin request through the `EdgeZero` router using the `"default"`
/// KV store label.
///
/// This is a low-level manual path. It does not read `edgezero.toml` and
/// therefore does not honor manifest gating for KV, config, or secret stores.
/// Prefer [`crate::run_app`] or [`dispatch_with_manifest`] for normal
/// manifest-aware dispatch.
///
/// # Errors
/// Propagates any error from [`dispatch_with_kv_label`].
#[inline]
pub async fn dispatch(app: &App, req: IncomingRequest) -> anyhow::Result<SpinResponse> {
    dispatch_with_kv_label(app, req, "default").await
}

/// Dispatch a Spin request using store settings resolved from `edgezero.toml`.
///
/// This is the manifest-aware manual entry point for callers that already have
/// an [`App`]. The `Hooks`-based [`crate::run_app`] helper uses the same
/// resolution path and additionally honors `Hooks::config_store()` metadata
/// generated by the `app!` macro.
///
/// # Errors
/// Returns any error propagated from the inner dispatch or response
/// translation.
#[inline]
pub async fn dispatch_with_manifest(
    app: &App,
    manifest_src: &str,
    req: IncomingRequest,
) -> anyhow::Result<SpinResponse> {
    let manifest_loader = ManifestLoader::load_from_str(manifest_src);
    let settings = resolve_store_settings(manifest_loader.manifest(), false);
    dispatch_with_store_settings(app, req, &settings).await
}

pub(crate) async fn dispatch_with_store_settings(
    app: &App,
    req: IncomingRequest,
    settings: &SpinStoreSettings,
) -> anyhow::Result<SpinResponse> {
    let stores = Stores {
        config_store: resolve_config_handle(settings.config_enabled),
        kv: resolve_kv_handle(&settings.kv_label, settings.kv_required)?,
        secrets: resolve_secret_handle(settings.secrets_enabled),
    };
    dispatch_with_handles(app, req, stores).await
}

/// Dispatch a Spin request through the `EdgeZero` router and return
/// a Spin-compatible response, opening the KV store under `kv_label`.
///
/// Injects all available stores into request extensions:
/// - `ConfigStoreHandle` backed by `SpinConfigStore` (Spin component variables)
/// - `KvHandle` backed by `SpinKvStore` opened on `kv_label` (best-effort;
///   logged and omitted if the label is not declared in `spin.toml`)
/// - `SecretHandle` backed by `SpinSecretStore` (Spin component variables)
///
/// Pass the label that matches your `spin.toml` `key_value_stores` entry.
/// If `[stores.kv.adapters.spin].name` in `edgezero.toml` is `"my-store"`,
/// that same string must appear in `spin.toml` and must be passed here.
///
/// # Errors
/// Returns an error if the inner dispatch or response translation fails.
#[inline]
pub async fn dispatch_with_kv_label(
    app: &App,
    req: IncomingRequest,
    kv_label: &str,
) -> anyhow::Result<SpinResponse> {
    let stores = Stores {
        config_store: resolve_config_handle(true),
        kv: resolve_kv_handle(kv_label, false)?,
        secrets: resolve_secret_handle(true),
    };
    dispatch_with_handles(app, req, stores).await
}

pub(crate) async fn dispatch_with_handles(
    app: &App,
    req: IncomingRequest,
    stores: Stores,
) -> anyhow::Result<SpinResponse> {
    let mut core_request = into_core_request(req).await?;
    if let Some(handle) = stores.config_store {
        core_request.extensions_mut().insert(handle);
    }
    if let Some(handle) = stores.kv {
        core_request.extensions_mut().insert(handle);
    }
    if let Some(handle) = stores.secrets {
        core_request.extensions_mut().insert(handle);
    }
    let response = app.router().oneshot(core_request).await?;
    Ok(from_core_response(response).await?)
}

fn resolve_config_handle(config_enabled: bool) -> Option<ConfigStoreHandle> {
    if !config_enabled {
        return None;
    }
    Some(ConfigStoreHandle::new(Arc::new(SpinConfigStore::new())))
}

fn resolve_kv_handle(kv_label: &str, kv_required: bool) -> anyhow::Result<Option<KvHandle>> {
    match SpinKvStore::open(kv_label) {
        Ok(store) => Ok(Some(KvHandle::new(Arc::new(store)))),
        Err(err) => {
            if kv_required {
                return Err(anyhow::anyhow!(
                    "Spin KV store '{kv_label}' is explicitly configured but could not be opened: {err}"
                ));
            }
            log::warn!(
                "SpinKvStore: could not open KV store (label {kv_label:?}); \
                 KV operations will be unavailable: {err}"
            );
            Ok(None)
        }
    }
}

fn resolve_secret_handle(secrets_enabled: bool) -> Option<SecretHandle> {
    if !secrets_enabled {
        return None;
    }
    Some(SecretHandle::new(Arc::new(SpinSecretStore::new())))
}

fn into_core_method(method: &SpinMethod) -> Result<CoreMethod, EdgeError> {
    match method {
        SpinMethod::Get => Ok(CoreMethod::GET),
        SpinMethod::Post => Ok(CoreMethod::POST),
        SpinMethod::Put => Ok(CoreMethod::PUT),
        SpinMethod::Delete => Ok(CoreMethod::DELETE),
        SpinMethod::Patch => Ok(CoreMethod::PATCH),
        SpinMethod::Head => Ok(CoreMethod::HEAD),
        SpinMethod::Options => Ok(CoreMethod::OPTIONS),
        SpinMethod::Connect => Ok(CoreMethod::CONNECT),
        SpinMethod::Trace => Ok(CoreMethod::TRACE),
        SpinMethod::Other(text) => CoreMethod::from_bytes(text.as_bytes()).map_err(|err| {
            EdgeError::bad_request(format!("unsupported HTTP method '{text}': {err}"))
        }),
    }
}
