//! Adapter helpers for Cloudflare Workers.

#[cfg(feature = "cli")]
pub mod cli;

#[cfg(all(feature = "cloudflare", target_arch = "wasm32"))]
pub mod config_store;
#[cfg(all(feature = "cloudflare", target_arch = "wasm32"))]
mod context;
#[cfg(all(feature = "cloudflare", target_arch = "wasm32"))]
mod proxy;
#[cfg(all(feature = "cloudflare", target_arch = "wasm32"))]
mod request;
#[cfg(all(feature = "cloudflare", target_arch = "wasm32"))]
mod response;

#[cfg(all(feature = "cloudflare", target_arch = "wasm32"))]
pub use config_store::CloudflareConfigStore;
#[cfg(all(feature = "cloudflare", target_arch = "wasm32"))]
pub use context::CloudflareRequestContext;
#[cfg(all(feature = "cloudflare", target_arch = "wasm32"))]
pub use proxy::CloudflareProxyClient;
#[cfg(all(feature = "cloudflare", target_arch = "wasm32"))]
pub use request::{dispatch, dispatch_with_config, into_core_request};
#[cfg(all(feature = "cloudflare", target_arch = "wasm32"))]
pub use response::from_core_response;

#[cfg(all(feature = "cloudflare", target_arch = "wasm32"))]
pub fn init_logger() -> Result<(), log::SetLoggerError> {
    Ok(())
}

#[cfg(not(all(feature = "cloudflare", target_arch = "wasm32")))]
pub fn init_logger() -> Result<(), log::SetLoggerError> {
    Ok(())
}

#[cfg(all(feature = "cloudflare", target_arch = "wasm32"))]
pub trait AppExt {
    fn dispatch<'a>(
        &'a self,
        req: worker::Request,
        env: worker::Env,
        ctx: worker::Context,
    ) -> ::core::pin::Pin<
        Box<dyn ::core::future::Future<Output = Result<worker::Response, worker::Error>> + 'a>,
    >;
}

#[cfg(all(feature = "cloudflare", target_arch = "wasm32"))]
impl AppExt for edgezero_core::app::App {
    fn dispatch<'a>(
        &'a self,
        req: worker::Request,
        env: worker::Env,
        ctx: worker::Context,
    ) -> ::core::pin::Pin<
        Box<dyn ::core::future::Future<Output = Result<worker::Response, worker::Error>> + 'a>,
    > {
        Box::pin(crate::request::dispatch(self, req, env, ctx))
    }
}

#[cfg(all(feature = "cloudflare", target_arch = "wasm32"))]
pub async fn run_app<A: edgezero_core::app::Hooks>(
    req: worker::Request,
    env: worker::Env,
    ctx: worker::Context,
) -> Result<worker::Response, worker::Error> {
    init_logger().expect("init cloudflare logger");
    let app = A::build_app();
    dispatch_app(
        &app,
        req,
        env,
        ctx,
        A::config_store().map(|cfg| cfg.name_for_adapter(edgezero_core::app::CLOUDFLARE_ADAPTER)),
    )
    .await
}

/// Run the app resolving the config store binding name from `manifest_src`.
///
/// Prefers hook metadata from [`edgezero_core::app::Hooks::config_store`]
/// and falls back to resolving `[stores.config]` from `manifest_src`.
///
/// # Deprecation
/// Apps generated by the `app!` macro already embed config-store metadata in
/// `Hooks::config_store()`. Prefer [`run_app`], which reads that metadata
/// directly and does not require passing the manifest source at runtime.
#[deprecated(
    note = "Use run_app instead. Config-store metadata is now embedded by the app!() macro \
            and read via Hooks::config_store(); passing manifest_src at runtime is no longer needed."
)]
#[cfg(all(feature = "cloudflare", target_arch = "wasm32"))]
pub async fn run_app_with_manifest<A: edgezero_core::app::Hooks>(
    manifest_src: &str,
    req: worker::Request,
    env: worker::Env,
    ctx: worker::Context,
) -> Result<worker::Response, worker::Error> {
    init_logger().expect("init cloudflare logger");
    let app = A::build_app();
    let binding_name = A::config_store()
        .map(|cfg| {
            cfg.name_for_adapter(edgezero_core::app::CLOUDFLARE_ADAPTER)
                .to_string()
        })
        .or_else(|| {
            let manifest = edgezero_core::manifest::ManifestLoader::load_from_str(manifest_src);
            manifest.manifest().stores.config.as_ref().map(|cfg| {
                cfg.config_store_name(edgezero_core::app::CLOUDFLARE_ADAPTER)
                    .to_string()
            })
        });
    dispatch_app(&app, req, env, ctx, binding_name.as_deref()).await
}

#[cfg(all(feature = "cloudflare", target_arch = "wasm32"))]
async fn dispatch_app(
    app: &edgezero_core::app::App,
    req: worker::Request,
    env: worker::Env,
    ctx: worker::Context,
    config_store_name: Option<&str>,
) -> Result<worker::Response, worker::Error> {
    if let Some(binding_name) = config_store_name {
        dispatch_with_config(app, req, env, ctx, binding_name).await
    } else {
        dispatch(app, req, env, ctx).await
    }
}
